### ISSUE TITLE
Letter API error object is preceded by a string. 

### ISSUE THREAD

**Issue by trevorhere** [lob/lob-ruby#178]
(Status 422) to.address_line1 is required or to must be a string 
 {
    "error": {
        "message": "to.address_line1 is required or to must be a string",
        "status_code": 422
    }
}

**Comment by itsachen** [comment]
Hi Trevor,

In Ruby, that is how the Lob error is printed by default. You can extract the error body by referring to the `json_body` attribute of the error rather than printing the error itself.

See the [`lob_error.rb`](https://github.com/lob/lob-ruby/blob/4db923ff5b5730c2c54667869a79d8b1188c6ade/lib/lob/errors/lob_error.rb) file for other properties that you can extract.
